// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi62B96JngrGIzmxMF9gL4P3X6jj8vbxc',
    appId: '1:572656431728:web:d67e9476d21dee0b563ab5',
    messagingSenderId: '572656431728',
    projectId: 'portailsalarie-d6993',
    authDomain: 'portailsalarie-d6993.firebaseapp.com',
    storageBucket: 'portailsalarie-d6993.appspot.com',
    measurementId: 'G-K3CXYZK1SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB358CtyWvTqk9p-P6_U1h-DHUX5XMtl_k',
    appId: '1:572656431728:android:24b191f703746a0d563ab5',
    messagingSenderId: '572656431728',
    projectId: 'portailsalarie-d6993',
    storageBucket: 'portailsalarie-d6993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUN3SalawqTrPOfWwdG6R9mP-9L7Vw6HM',
    appId: '1:572656431728:ios:5bef433253fc3b3c563ab5',
    messagingSenderId: '572656431728',
    projectId: 'portailsalarie-d6993',
    storageBucket: 'portailsalarie-d6993.appspot.com',
    iosBundleId: 'com.bmsoft.portailsalarie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUN3SalawqTrPOfWwdG6R9mP-9L7Vw6HM',
    appId: '1:572656431728:ios:cae2b31bc5a18c4a563ab5',
    messagingSenderId: '572656431728',
    projectId: 'portailsalarie-d6993',
    storageBucket: 'portailsalarie-d6993.appspot.com',
    iosBundleId: 'com.example.portailSalarie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi62B96JngrGIzmxMF9gL4P3X6jj8vbxc',
    appId: '1:572656431728:web:d7c6c5414f3156ad563ab5',
    messagingSenderId: '572656431728',
    projectId: 'portailsalarie-d6993',
    authDomain: 'portailsalarie-d6993.firebaseapp.com',
    storageBucket: 'portailsalarie-d6993.appspot.com',
    measurementId: 'G-3RELMD7277',
  );
}
